version: '3.8'

services:
  db:
    container_name: pg_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:  ${POSTGRES_DB:-car_rent}
    ports:
      - "5432:5432"